name: hop_docgen
version: 0.0.1-dev.1
author: Kevin Moore <kevmoo@google.com>
description: Hop task for creating, publishing, and updating documentation for your Dart project
homepage: https://github.com/kevmoo/hop_docgen
environment:
  sdk: '>=1.2.0-dev.4.0 <2.0.0'
dependencies:
  git: '>=0.1.0 <0.2.0'
  hop: '>=0.29.0'
dev_dependencies:
  unittest: any
