name: hop_docgen
version: 0.1.3-dev
author: Kevin Moore <kevmoo@google.com>
description: Hop task for creating, publishing, and updating documentation for your Dart project
homepage: https://github.com/kevmoo/hop_docgen
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.11.0'
  git: '>=0.2.1 <0.3.0'
  hop: '>=0.30.2 <0.31.0'
dev_dependencies:
  scheduled_test: '>=0.10.0 <0.11.0'
