name: hop_docgen
version: 0.0.1-dev
author: kevmoo@google.com
description: Hop task for creating, publishing, and updating documentation for your Dart project
homepage: https://github.com/kevmoo/hop_docgen
environment:
  sdk: '>=1.2.0-dev.4.0 <2.0.0'
dependencies:
  hop: '>=0.29.0'
dev_dependencies:
  unittest: any
