name: hop_docgen
version: 0.1.3+2
author: Kevin Moore <kevmoo@google.com>
description: Hop task for creating, publishing, and updating documentation for your Dart project
homepage: https://github.com/kevmoo/hop_docgen
environment:
  sdk: '>=1.2.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.13.0'
  bot_io: '>=0.26.3 <0.27.0'
  git: '>=0.2.1 <0.5.0'
  hop: '>=0.30.2 <0.32.0'
dev_dependencies:
  hop_unittest: '>=0.1.0 <0.2.0'
  scheduled_test: '>=0.10.0 <0.12.0'
